### ISSUE TITLE
Completely unable to individually download any of the DXFs. Insanely annoying. 

### ISSUE THREAD

**Issue by Artesian3D** [seemecnc/RostockMAXv2#1]
Just giant piles of gibberish text whenever any of the links are clicked. Where is a simple download button!?

**Comment by geneb** [comment]
That's not how github works.  The simplest way for you to get the files you need is to go to the top level of the repository and click the green "Clone or Download" dropdown and pick "Download Zip".  You'll get the whole repository.

That being said, if you REALLY don't want to download the whole repo, you can click on the DXF you want, copy all the text and then paste it into notepad and save it as <whatever>.DXF.  The DXF format is just a text file - so this should work fine.
